// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierProductExercise.Business.Context;

#nullable disable

namespace SupplierProductExercise.Business.Migrations
{
    [DbContext(typeof(SupplierProductDbContext))]
    partial class SupplierProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplierProductExercise.Business.Entities.SupplierProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("SupplierProduct", "SupplierProductExercise");
                });

            modelBuilder.Entity("SupplierProductExercise.Business.Entities.SupplierProductVariant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("bit");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierProductID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SupplierProductID");

                    b.HasIndex("Code", "SupplierProductID")
                        .IsUnique();

                    b.ToTable("SupplierProductVariant", "SupplierProductExercise");
                });

            modelBuilder.Entity("SupplierProductExercise.Business.Entities.SupplierServiceParameter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BearerToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Service")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Service")
                        .IsUnique();

                    b.ToTable("SupplierServiceParameter", "SupplierProductExercise");
                });

            modelBuilder.Entity("SupplierProductExercise.Business.Entities.SupplierProductVariant", b =>
                {
                    b.HasOne("SupplierProductExercise.Business.Entities.SupplierProduct", null)
                        .WithMany("Variants")
                        .HasForeignKey("SupplierProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupplierProductExercise.Business.Entities.SupplierProduct", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
